version: '{build}'
os: Windows Server 2012
init:
  - ps:
      iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - ps: 
      |      
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip',
          'C:\apache-maven-3.3.9-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\apache-maven-3.3.9-bin", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.3.9\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - mvn clean package --batch-mode sonar:sonar -Dsonar.host.url=https://sonarqube.com:443 -Dsonar.login=bd17494f9769dec8a9baaa0f5143be1924b07ecf -Dsonar.issuesReport.html.enable=true -Dsonar.analysis.mode=issues
test: off
artifacts:
  - path: \target\hp-application-automation-tools-plugin.hpi
    name: hp-application-automation-tools-plugin.hpi
  - path: \target\sonar\issues-report
    name: Sonar html report (reprot-light.html - only new issues, reprot.html)
    type: zip
cache:
  - C:\maven\
  - C:\sonarlint\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.sonar\cache
  
